---
docker_edition: ce
docker_package_state: present
docker_service_state: started

docker_install_compose: true
docker_daemon_options:
  metrics-addr: "0.0.0.0:9323"
  # TODO: enable syslog when syslog server is created
  # log-driver: syslog
  # log-opts:
  #   syslog-address: "tcp://{{ syslog_host }}:514"
  #   tag: c-{{ '{{' }}.Name{{ '}}' }}
  #   syslog-format: rfc5424
  default-address-pools:
    - base: 172.16.0.0/12
      size: 26

docker_compose_cadvisor:
  cadvisor:
    cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.51.0
      command:
        - '-housekeeping_interval=30s'
        - '-docker_only=true'
      ports:
        - 9338:8080
      volumes:
        - type: bind
          source: /
          target: /rootfs
          read_only: true
          bind:
            propagation: rslave
        - type: bind
          source: /var/lib/docker/
          target: /var/lib/docker
          read_only: true
          bind:
            propagation: rslave
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /dev/disk/:/dev/disk:ro
