---
- name: Copy docker-compose.service template
  ansible.builtin.template:
    src: templates/systemd-docker-compose.service.j2
    dest: "/etc/systemd/system/docker-compose@.service"
    owner: root
    group: root
    mode: "0644"

- name: Include task to create service
  ansible.builtin.include_tasks: single-compose.yml
  when: '"present" == (item.value.state | d("present"))'
  loop: "{{ systemd_docker_compose_services | dict2items }}"

- name: Cleanup
  ansible.builtin.include_tasks: single-compose-decomission.yml
  when: '"absent" == (item.value.state | d("present"))'
  loop: "{{ systemd_docker_compose_services | dict2items }}"
