---
roles:
  - name: geerlingguy.docker

collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: ansible.utils
  - name: community.docker
  - name: community.proxmox
