systemd_docker_compose_services:
  sbb-pipeline-postgres:
    postgres:
      image: postgres:16
      ports:
        - "5432:5432"
      env:
        POSTGRES_DB: sbb_precipitation
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "{{ vault_data_processing_postgres_password }}"
        TZ: Europe/Zurich
      volumes:
        - "./postgres-data:/var/lib/postgresql/data:rw"
      healthcheck:
        test:
          - CMD-SHELL
          - pg_isready -U postgres -d sbb_precipitation
        interval: 10s
        timeout: 5s
        retries: 10
