---
- hosts: dyndns01
  become: true
  tasks:
    - name: Ensure cron package is installed
      ansible.builtin.package:
        name: cron
        state: present
      tags: dyndns-imk

    - name: Check whether crontab is available
      ansible.builtin.command: which crontab
      register: crontab_cmd
      changed_when: false
      failed_when: false
      check_mode: false
      tags: dyndns-imk

    - name: Copy dyndns-imk bash script
      ansible.builtin.copy:
        src: files/dyndns-imk
        dest: /home/gigu/dyndns-imk.sh
        owner: gigu
        group: gigu
        mode: '0755'
      tags: dyndns-imk

    - name: Create cronjob for dyndns-imk script
      ansible.builtin.cron:
        name: Update dyndns daily
        minute: "05"
        hour: "6"
        job: "~/dyndns-imk.sh -u {{ dyndns_imk.user }} -p {{ dyndns_imk.password }} -d {{ dyndns_imk.domain }}"
        user: gigu
      when: crontab_cmd.rc == 0
      tags: dyndns-imk
