---
- hosts: nsupdate01
  become: true
  roles:
    - role: wireguard-client
      tags: wireguard
  tasks:
    - name: Copy nsupdate bash script
      ansible.builtin.copy:
        src: files/nsupdate
        dest: /home/gigu/nsupdate.sh
        owner: gigu
        group: gigu
        mode: '0755'
      tags: nsupdate

    - name: Create cronjob for nsupdate script
      ansible.builtin.cron:
        name: Update ddyn daily
        minute: "0"
        hour: "6"
        job: "~/nsupdate.sh -k {{ nsupdate.key }} -f {{ nsupdate.secret_key }} -d {{ nsupdate.domain }} -z {{ nsupdate.zone }} -s {{ nsupdate.server }}"
        user: gigu
      tags: nsupdate
